# Request - Information of Marker to add, and ID of marker to move in front of
float64 lat
float64 lon
float64 alt
float32 waypoint_error
string marker_type
uint8 aruco_id
uint8 aruco_id_2
uint8 new_following_marker_id
---
# Response - T/F
bool success
